parameters:
    certy_certification_builder_class: Certificationy\Component\Certy\Builder\Builder
    certy_certification_provider_registry_class: Certificationy\Component\Certy\Provider\ProviderRegistry
    certy_certification_providers_builder_pass_class: Certificationy\Component\Certy\Builder\ProviderBuilderPass
    certy_certification_abstract_loader_class: Certificationy\Component\Certy\Loader\Loader
    certy_certification_file_loader_class: Certificationy\Component\Certy\Loader\FileLoader
    certy_certification_php_loader_class: Certificationy\Component\Certy\Loader\PhpLoader
    certy_certification_abstract_dumper_class: Certificationy\Component\Certy\Dumper\AbstractDumper
    certy_certification_file_dumper_class: Certificationy\Component\Certy\Dumper\FileDumper
    certy_certification_php_dumper_class: Certificationy\Component\Certy\Dumper\PhpDumper
    certy_certification_factory_class: Certificationy\Component\Certy\Factory\CertificationFactory
    certy_certification_collection_handler: Certificationy\Component\Certy\Model\Serializer\ModelCollectionHandler
    certy_certification_collection_deserialize: Certificationy\Component\Certy\Model\Serializer\CertificationBuildSubscriber
    certy_certification_context: Certificationy\Component\Certy\Context\CertificationContext

services:
    certy.certification.builder:
        class: %certy_certification_builder_class%

    certy.certification.context:
        class: %certy_certification_context%
        calls:
            - [ "setDebug", [ %kernel.debug% ] ]

    certy.certification.provider_registry:
        class: %certy_certification_provider_registry_class%

    certy.certification.loader.abstract:
        class: %certy_certification_abstract_loader_class%
        abstract: true

    certy.certification.loader.file:
        class: %certy_certification_file_loader_class%
        parent: certy.certification.loader.abstract
        arguments:
            - %kernel.cache_dir%
            - 'certificationy'

    certy.certification.loader.php:
        class: %certy_certification_php_loader_class%
        parent: certy.certification.loader.file

    certy.certification.dumper.abstract:
        class: %certy_certification_abstract_dumper_class%
        abstract: true

    certy.certification.dumper.file:
        class: %certy_certification_file_dumper_class%
        parent: certy.certification.dumper.abstract
        arguments:
            - %kernel.cache_dir%
            - 'certificationy'

    certy.certification.dumper.php:
        class: %certy_certification_php_dumper_class%
        parent: certy.certification.dumper.file

    certy.certification.factory:
        class: %certy_certification_factory_class%
        calls:
            - [ "setBuilder", [ @certy.certification.builder ] ]
            - [ "setDumper", [ @certy.certification.dumper.php ] ]
            - [ "setLoader", [ @certy.certification.loader.php ] ]
            - [ "setProviderRegistry", [ @certy.certification.provider_registry ] ]

    certy.certification.collection.handler:
        class: %certy_certification_collection_handler%
        tags:
            - { name: jms_serializer.subscribing_handler }

    certy.certification.collection.deserialize:
        class: %certy_certification_collection_deserialize%
        tags:
            - { name: jms_serializer.event_subscriber }


    certy.certification.json.provider:
        class: Certificationy\Component\Certy\Provider\JsonProvider
        calls:
            - [ "setOptions", [ { path: %certy_file_provider_root_dir% } ] ]
        tags:
            - { name: certy.provider }

    certy.certification.yaml.provider:
        class: Certificationy\Component\Certy\Provider\YamlProvider
        calls:
            - [ "setOptions", [ { path: %certy_file_provider_root_dir% } ] ]
        tags:
            - { name: certy.provider }
