parameters:
    certy_certification_submission_compute_listener_class: Certificationy\Component\Certy\EventListener\CertificationComputeResultListener
    certy_certification_context_listener: Certificationy\Component\Certy\EventListener\ContextListener
    certy_certification_context_score_listener: Certificationy\Component\Certy\EventListener\ContextScoreListener
    certy_certification_timer_listener: Certificationy\Component\Certy\EventListener\TimerListener

services:
    certy.certification.timer.listener:
        class: %certy_certification_timer_listener%
        tags:
            - { name: kernel.event_listener, event: certy.certification.start, method: startTimer }
            - { name: kernel.event_listener, event: certy.certification.submission, method: stopTimer }

    certy.certification.submission_compute.listener:
        class: %certy_certification_submission_compute_listener_class%
        arguments:
            - @certy.certification.calculator_manager
            - @event_dispatcher
        tags:
            - { name: kernel.event_listener, event: certy.certification.submission, method: onSubmission }

    certy.certification.context.listener:
        class: %certy_certification_context_listener%
        tags:
            - { name: kernel.event_listener, event: certy.certification.custom_context, method: removeCategories, priority: 10 }
            - { name: kernel.event_listener, event: certy.certification.custom_context, method: removeQuestions, priority: 5 }

    certy.certification.context_score.listener:
        class: %certy_certification_context_score_listener%
        tags:
            - { name: kernel.event_listener, event: certy.certification.custom_context, method: updateScore, priority: -10 }
